### ISSUE TITLE
run testapp error

### ISSUE THREAD

**Issue by aadog** [SkliarOleksandr/DelphiAST#1]
atl parse
===================================================================
compile fail
Error [(1, 1)]: Token "UNIT" expected

ast parse rtl
===================================================================
compile fail
Error [System(424, 42)]: Token "}" expected but "CLOSE ROUND" found
Error [System(4654, 16)]: The included file: GETMEM.INC has errors

**Comment by SkliarOleksandr** [comment]
It isn't ready for now, I am working on it (now the progress of parsing System.pas = up to 13000 line)

**Comment by AdrianV** [comment]
have you already solved the problem of `PByte - PByte` returns `PByte` and not a `NativeInt` ?

**Comment by SkliarOleksandr** [comment]
Hi, this issue is solved now, the progress: System: 13082
